#!/bin/bash
cat << EOF > acrostic.txt
Elizabeth it is in vain you say
Love not"—thou sayest it in so sweet a way:
In vain those words from thee or L.E.L.
Zantippe's talents had enforced so well:
Ah! if that language from thy heart arise,
Breath it less gently forth—and veil thine eyes.
Endymion, recollect, when Luna tried
To cure his love—was cured of all beside—
His follie—pride—and passion—for he died.
EOF
awk '{printf substr($0, 1, 1)} END{print ""}' acrostic.txt
rm acrostic.txt

